#ifndef _FULTRON_FS_CONFIG_H
#define _FULTRON_FS_CONFIG_H

#define FULTRONFS_BLOCK_SIZE_BYTES   (512ULL)
#define FULTRONFS_DIRECT_BLOCK_COUNT (5ULL)
#define FULTRONFS_DATA_BLOCK_COUNT   (1024ULL)

#define FULTRONFS_INODES_PER_BLOCK   (FULTRONFS_BLOCK_SIZE_BYTES / sizeof(inode_t))
#define FULTRONFS_POINTERS_PER_BLOCK (FULTRONFS_BLOCK_SIZE_BYTES / sizeof(inode_t))

#endif /* _FULTRON_FS_CONFIG_H */