[package]
name = "fultronos"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.6.14"
panic-halt = "0.2.0"

[build-dependencies]
cc = "1.0"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = true  # Ensure debug symbols are included in release builds
