cc_library(
    name = "ethernet",
    srcs = [
        "xemacps_bdring.c",
        "xemacps_control.c",
        "xemacps_g.c",
        "xemacps_hw.c",
        "xemacps_intr.c",
        "xemacps_sinit.c",
        "xemacps.c",
    ],
    hdrs = [
        "xemacps_bd.h",
        "xemacps_bdring.h",
        "xemacps_hw.h",
        "xemacps.h",
        "xil_types.h",
    ],
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
)