[target.aarch64-unknown-none]
linker = "aarch64-linux-gnu-gcc"
runner = "./run.sh"

[build]
target = "aarch64-unknown-none"

[unstable]
build-std = ["alloc", "compiler_builtins", "core"]
build-std-features = ["compiler-builtins-mem"]
