cc_library(
    name = "zynq",
    srcs = [
        "_start.s",
    ],
    deps = [
        "//source/drivers/uartps:uartps",
        "//source/lib/libfc:libfc",
    ],
    visibility = ["//visibility:public"],
)