cc_library(
    name = "xbspconfig",
    srcs = [
    ],
    hdrs = [
        "bspconfig.h",
    ],
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "xparameters",
    srcs = [
    ],
    hdrs = [
        "xparameters.h",
    ],
    includes = [
        ".",
    ],
    visibility = ["//visibility:public"],
)